version: '3.8'

services:
  api-meteo:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: api-meteo
    volumes:
      - .:/app
    environment:
      - PORT=${PORT}
      - SECRET_KEY=${SECRET_KEY}
      - SECRET_COOKIE=${SECRET_COOKIE}
      - CHOKIDAR_USEPOLLING=true
    ports:
      - ${PORT}:${PORT}
    networks:
      - meteo-network
    depends_on:
      - mongodb-meteo
    restart: always

  mongodb-meteo:
    image: mongo:latest
    container_name: mongodb-meteo
    volumes:
      - ./mongo-data:/data/db
    networks:
      - meteo-network
    expose:
      - ${PORT_BDD}

networks:
  meteo-network:
    driver: bridge

volumes:
  mongo-data: